### ISSUE TITLE
Hard crash

### ISSUE THREAD

**Issue by pyrsmk** [MicahCarrick/gedit-restore-tabs#1]
Hi,

After activate your plugin and restart gedit, I've this:

```
(gedit:6645): Gtk-CRITICAL **: gtk_list_store_set_column_types: assertion `priv->columns_dirty == 0' failed
(gedit:6645): GLib-GIO-CRITICAL **: Settings schema 'org.gnome.gedit.plugins.restoretabs' is not installed
(gedit:6645): GLib-GIO-CRITICAL **: g_settings_get_key_info: assertion `settings->priv->schema != NULL' failed
zsh: segmentation fault  gedit
```

**Comment by Quixotix** [comment]
Did you follow the instructions in the README https://github.com/Quixotix/gedit-restore-tabs/blob/master/README.markdown ?

Specifically the part about compiling the GSettings schema file?

cp org.gnome.gedit.plugins.restoretabs.gschema.xml /usr/share/glib-2.0/schemas/
glib-compile-schemas /usr/share/glib-2.0/schemas/

**Comment by pyrsmk** [comment]
Arf... Sorry, I was too quick...

Then!

The first run with your plugin seems to hang on (we can see a non saved tab with a nice loader which turns without end). The other runs are perfect ;)
